name: your_money
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.7
  uuid: ^4.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  intl: ^0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
